apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: historical-job-raw-2
  namespace: processing
spec:
  volumes:
    - name: ivy
      emptyDir: {}
  sparkConf:
    #extraJavaOptions: -Dcom.amazonaws.services.s3.enableV4=true
    #spark.jars.packages: "org.apache.hadoop:hadoop-aws:2.7.3,org.apache.spark:spark-avro_2.12:3.0.1"
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
    spark.kubernetes.allocation.batch.size: "10"
  hadoopConf:
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  type: Python
  pythonVersion: "3"
  mode: cluster
  #image: "docker.io/neylsoncrepalde/spark-operator:v3.0.0-aws"
  #image: "docker.io/neylsoncrepalde/spark-operator:v3.1.1-hadoop3-aws-kafka"
  image: "docker.io/igoraugustoms91/spark-operator-spotipy:v2"
  imagePullPolicy: Always
  mainApplicationFile: s3a://datalake-igti-igor/code/historical-job-raw.py
  #sparkVersion: "3.0.0"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
      CLIENT_ID_SPOTIPY:
        name: spotipy-credentials
        key: client_id_spotipy
      CLIENT_SECRET_SPOTIPY:
        name: spotipy-credentials
        key: client_secret_spotipy
    cores: 1
    coreLimit: "1200m"
    #memory: "4g"
    memory: "2g"
    labels:
      #version: "3.0.0"
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: ivy
        mountPath: /tmp
  executor:
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
      CLIENT_ID_SPOTIPY:
        name: spotipy-credentials
        key: client_id_spotipy
      CLIENT_SECRET_SPOTIPY:
        name: spotipy-credentials
        key: client_secret_spotipy        
    #cores: 3
    cores: 1
    #instances: 4
    instances: 5
    #memory: "4g"
    memory: "1g"
    labels:
      #version: "3.0.0"
      version: 3.1.1
    volumeMounts:
      - name: ivy
        mountPath: /tmp